### PR TITLE
Include Definitions for Module Exports in index.d.ts

### LINKED ISSUE #91: Typescript error when importing from @cypress/skip-test
Importing like this

```typescript
import { onlyOn, skipOn } from '@cypress/skip-test';
```

Gives me the error:
> TS2306: File 'node_modules/@cypress/skip-test/index.d.ts' is not a module.

While running `tsc --traceResolution` reports the following:
<details>

```
======== Resolving module '@cypress/skip-test' from 'src/pages/EServices/components/GeneralInformation/GeneralInformation.spec.tsx'. ========
Explicitly specified module resolution kind: 'NodeJs'.
'baseUrl' option is set to 'src', using this value to resolve non-relative module name '@cypress/skip-test'.
Resolving module name '@cypress/skip-test' relative to base url 'src' - 'src/@cypress/skip-test'.
Loading module as file / folder, candidate module location 'src/@cypress/skip-test', target file type 'TypeScript'.
Loading module '@cypress/skip-test' from 'node_modules' folder, target file type 'TypeScript'.
Directory 'src/pages/EServices/components/GeneralInformation/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'cypress__skip-test'
Directory 'src/pages/EServices/components/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'cypress__skip-test'
Directory 'src/pages/EServices/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'cypress__skip-test'
Directory 'src/pages/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'cypress__skip-test'
Directory 'src/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'cypress__skip-test'
Directory 'node_modules/@types' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'cypress__skip-test'
Directory 'packages/node_modules' does not exist, skipping all lookups in it.
Scoped package detected, looking in 'cypress__skip-test'
Found 'package.json' at 'node_modules/@cypress/skip-test/package.json'.
'package.json' does not have a 'typesVersions' field.
File 'node_modules/@cypress/skip-test.ts' does not exist.
File 'node_modules/@cypress/skip-test.tsx' does not exist.
File 'node_modules/@cypress/skip-test.d.ts' does not exist.
'package.json' does not have a 'typings' field.
'package.json' has 'types' field 'index.d.ts' that references 'node_modules/@cypress/skip-test/index.d.ts'.
File 'node_modules/@cypress/skip-test/index.d.ts' exist - use it as a name resolution result.
Resolving real path for 'node_modules/@cypress/skip-test/index.d.ts', result 'node_modules/@cypress/skip-test/index.d.ts'.
======== Module name '@cypress/skip-test' was successfully resolved to 'node_modules/@cypress/skip-test/index.d.ts' with Package ID '@cypress/skip-test/index.d.ts@2.5.0'. ========
```

</details>

### PR DESCRIPTION
**Pull request by lrhacker**
## Summary
Fixes #91

This change describes the exports from `index.js` in `index.d.ts`, so that TypeScript can properly resolve `import` statements for the module. It also includes running the format command on the `index.d.ts` file.

## Details
I was seeing the "File 'node_modules/@cypress/skip-test/index.d.ts' is not a module." error when trying to add
```typescript
import { onlyOn } from '@cypress/skip-test';
```
to a test file in my project that was written using TypeScript. By modifying `index.d.ts` with the changes in this PR, I was able to resolve the error.

Test file in `cypress/integration/sample_spec.ts`:
```typescript
import { onlyOn, skipOn, isOn } from '@cypress/skip-test'; // This import previous resulted in an error

onlyOn('mac', () => {
  // this callback will only evaluate on Mac
  // thus the tests will be completely hidden from other platforms
  describe('Mac tests', () => {
    it('works', () => {
      Cypress.log({name: 'On Mac?', message: isOn('mac')});
      Cypress.log({name: 'On Windows?', message: isOn('windows')});
    });
  });
});

onlyOn('windows', () => {
  // this callback will only evaluate on Windows
  // thus the tests will be completely hidden from other platforms
  describe('Windows tests', () => {
    it('works', () => {
      Cypress.log({name: 'On Mac?', message: isOn('mac')});
      Cypress.log({name: 'On Windows?', message: isOn('windows')});
    });
  });
});

skipOn('mac', () => {
  // this test will run on every platform but Mac
  it('hides this test on Mac', () => {});
});
```
Test output:
image

My Cypress `tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress"],
  },
  "include": [
    "**/*.ts"
  ]
}
```

My project's root `tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es2019",
    "lib": ["es2019", "dom"],
    "module": "commonjs",
    "skipLibCheck": true,
  },
  "include": [
    "**/*.ts"
  ],
}
```

### CODE REVIEW

**Review by agugut — APPROVED** [review]

**Comment by KiaFarhang** [comment]
Hi @lrhacker - thanks so much for opening this! Do you know if there are plans to merge it? We're running into the same TypeScript issues and would love for this PR to merge and solve them. CCing @bahmutov to get your thoughts as well.

Appreciate the time working on this!

**Comment by lrhacker** [comment]
Thank you, @KiaFarhang! I have not heard one way or another about it being merged yet, but I am keeping an eye on it if there turn out to be any changes needed!

**Comment by MCFreddie777** [comment]
Will this be merged anytime soon?

**Comment by bahmutov** [comment]
Super, thank you

**Comment by F3n67u** [comment]
How can I use cy.skipOn without import `@cypress/skip-test`

**Pull request merged**
